name: test for main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-Dwarnings"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Build artifacts
        uses: Swatinem/rust-cache@v2.7.5
        with:
          cache-on-failure: true
          shared-key: ${{ github.event.pull_request.number || github.ref }}

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo build
        run: cargo build --all

      - name: Run clippy
        run: cargo clippy --all --all-targets --verbose -- -D warnings

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run tests
        run: cargo test --all --verbose
        env:
          RUST_BACKTRACE: 1
